version: '3.3'
services:
    db:
        container_name: my_db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - 64:64
        volumes:
            - db-data:/var/lib/mysql
    apache:
        container_name: my_apache
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - db
        ports:
            - 80:80
        volumes:
            - .:/var/www/html
    admin:
        container_name: phpmyadmin
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITARY=1
volumes:
    db-data:
